version: '3.3'

networks:
  linker:

services:
  webapp:
    build:
      context: ./
      dockerfile: mydocker.Dockerfile
    restart: always
    networks:
      - linker
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    ports:
      - 5000:5000

  mongodb:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongo_data:/data/db
    networks:
      - linker
    ports:
      - 27017:27017